import PyPDF2
file = open('step1','rb')
reader = PyPDF2.PdfFileReader(file)
page = reader.getPage(0)
lease = page.extractText()
leasel = lease.split()
propname = [' '.join(leasel[9:12])]
res_s = [' '.join(leasel[19:23])]
unit_t = [' '.join(leasel[105:110])]
unit = (leasel[111])
unit = unit[0:4]
s_date = (leasel[118])
s_date = s_date[0:10]
e_date = (leasel[123])
e_date = e_date[0:10]
m_rent = (leasel[135])
m_rent = m_rent[0:8]
m_parking = (leasel[142])
m_parking = m_parking[0:2]
d_occ = (leasel[144])
d_occ = d_occ[0:2]
short_tp = (leasel[147])
short_tp = short_tp[0:2]
lease_rent = [''.join(leasel[177:178])]
equal_m = (leasel[186])
app_fee = (leasel[235])
app_fee = app_fee[0:5]
add_fee = (leasel[237])
add_fee = add_fee[0:5]
sec_dep = (leasel[239])
sec_dep = sec_dep[0:5]
m_concess = (leasel[258])
one_concess = (leasel[273])
guarantor_n = (leasel[338])
audit = {"Property","Resident(s)","Apartment Unit Type","Unit Number","Lease Term","Base Rent","Pert Rent","Short Term Premium","Furniture Fee","Double Occupancy Premium","Base Rent","Payable for Lease Term","Equal Monthly installments","Application Fee","Administrative Fee","Security Deposit","Pet Deposit","Rent Concession","Rent Credit","Guarantor's Name"}
leasedata = [propname,res_s,unit_t,unit,s_date,e_date,m_rent,m_parking,d_occ,short_tp,lease_rent, equal_m,app_fee,add_fee,sec_dep,m_concess,guarantor_n]
print(leasedata)
